version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: angular_blog_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: enpei
      POSTGRES_PASSWORD: Pei830509
      POSTGRES_DB: angular_blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
