services:
  postgres:
    image: postgres:17-alpine
    container_name: angular_blog_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: enpei
      POSTGRES_PASSWORD: Pei830509
      POSTGRES_DB: angular_blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: angular_blog_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://enpei:Pei830509@postgres:5432/angular_blog_db
    depends_on:
      - postgres

volumes:
  postgres_data:
