server {
    listen 80;
    server_name admin.enpei.com.tw;
    root /var/www/admin.enpei.com.tw;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    gzip_vary on;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
